### ISSUE TITLE
Unable to play Spotify playlists

### ISSUE THREAD

**Issue by HTF8** [hmes98318/Music-Disc#11]
**Describe the bug**
The bot crashes when trying to play a Spotify playlist, producing the below error.  Single Spotify songs work fine.

```
D:\Programs\Discord Bot\node_modules\discord-player\dist\Player.js:432
                    playlist.tracks = spotifyPlaylist.tracks.items.map((m) => {
                                                             ^

TypeError: Cannot read properties of undefined (reading 'items')
    at Player.search (D:\Programs\Discord Bot\node_modules\discord-player\dist\Player.js:432:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.execute (D:\Programs\Discord Bot\src\commands\play.js:14:21)
```

**To Reproduce**

1. Try to play a Spotify playlist (ex: `+play https://open.spotify.com/album/0jo2HJc2mEB0WEiy1MS3Ju?si=h3l7FG_MQ3Wx-1dr8uQfMw`)
2. If a song is already playing, it will stop
3. The bot will crash, citing error `TypeError: Cannot read properties of undefined (reading 'items')`

**Expected behavior**
The bot should play the Spotify playlist.

**Screenshots**
Successfully playing a single track from Spotify:
![image](https://user-images.githubusercontent.com/33886223/208568171-1a1a1b39-2c92-4851-b9fa-aaa14c8c80cd.png)
Failing to play a playlist:
![image](https://user-images.githubusercontent.com/33886223/208568220-273ed379-c503-4315-81ce-f4fbb13bac5c.png)
YouTube playlists are still fine:
![image](https://user-images.githubusercontent.com/33886223/208568284-90bc1211-34db-4369-9ae2-6585215ee883.png)

**Version Information:**
 - Node.js: 16.17.1
 - Discord.js: 14.7.1
 - Music-Disc: 1.2.4
 - Dependency modules
     * discord-player: 5.3.2
     * ffmpeg-static: 5.1.0
     * opusscript: 0.0.8

**Additional context**
Bot has also recently been crashing occasionally while idle, citing the following error:
```
D:\Programs\Discord Bot\node_modules\discord.js\src\util\Components.js:90
      throw new Error(`Found unknown component type: ${data.type}`);
      ^

Error: Found unknown component type: 5
    at createComponent (D:\Programs\Discord Bot\node_modules\discord.js\src\util\Components.js:90:13)
    at D:\Programs\Discord Bot\node_modules\discord.js\src\structures\ActionRow.js:21:43
    at Array.map (<anonymous>)
    at new ActionRow (D:\Programs\Discord Bot\node_modules\discord.js\src\structures\ActionRow.js:21:34)
    at createComponent (D:\Programs\Discord Bot\node_modules\discord.js\src\util\Components.js:82:14)
    at D:\Programs\Discord Bot\node_modules\discord.js\src\structures\Message.js:156:50
    at Array.map (<anonymous>)
    at Message._patch (D:\Programs\Discord Bot\node_modules\discord.js\src\structures\Message.js:156:41)
    at new Message (D:\Programs\Discord Bot\node_modules\discord.js\src\structures\Message.js:50:10)
    at MessageManager._add (D:\Programs\Discord Bot\node_modules\discord.js\src\managers\CachedManager.js:44:32)
```

**Comment by hmes98318** [comment]
> **Additional context** Bot has also recently been crashing occasionally while idle, citing the following error:
> 
> ```
> D:\Programs\Discord Bot\node_modules\discord.js\src\util\Components.js:90
>       throw new Error(`Found unknown component type: ${data.type}`);
>       ^
> 
> Error: Found unknown component type: 5
>     at createComponent (D:\Programs\Discord Bot\node_modules\discord.js\src\util\Components.js:90:13)
>     at D:\Programs\Discord Bot\node_modules\discord.js\src\structures\ActionRow.js:21:43
>     at Array.map (<anonymous>)
>     at new ActionRow (D:\Programs\Discord Bot\node_modules\discord.js\src\structures\ActionRow.js:21:34)
>     at createComponent (D:\Programs\Discord Bot\node_modules\discord.js\src\util\Components.js:82:14)
>     at D:\Programs\Discord Bot\node_modules\discord.js\src\structures\Message.js:156:50
>     at Array.map (<anonymous>)
>     at Message._patch (D:\Programs\Discord Bot\node_modules\discord.js\src\structures\Message.js:156:41)
>     at new Message (D:\Programs\Discord Bot\node_modules\discord.js\src\structures\Message.js:50:10)
>     at MessageManager._add (D:\Programs\Discord Bot\node_modules\discord.js\src\managers\CachedManager.js:44:32)
> ```

Try update Bot to `v1.2.5`.
this version fixed button crash issue.

**Comment by HTF8** [comment]
That fixed it.  Thank you for your quick assistance.

Haven't had any crashes since updating to 1.2.5.

👍
