### ISSUE TITLE
[FEATURE SUGGESTION] Add buttons

### ISSUE THREAD

**Issue by DarkVibes2022** [hmes98318/Music-Disc#13]
Please add buttons to the embed which tells what music is playing

Like this:
![az_recorder_20230319_150958_edited](https://user-images.githubusercontent.com/77442205/226159857-fe46777f-6bec-48b8-b702-ff8d23193722.jpg)

**Comment by hmes98318** [comment]
Thanks for the suggestion! I'll add this feature in the next version.
