### ISSUE TITLE
Bot crashes when playing age-restricted video

### ISSUE THREAD

**Issue by OR1GG1N2** [hmes98318/Music-Disc#14]
![image](https://user-images.githubusercontent.com/83551876/226704427-9f5993b1-cf7a-45b5-901f-6905559f442b.png)
+-----------------------+
| Bot: v1.3.0               |
| Node.js: v18.13.0     |
| Discord.js: v14.8.0    |
+-----------------------+

**Comment by hmes98318** [comment]
https://github.com/Androz2091/discord-player/issues/1691
