### ISSUE TITLE
v1.3.1 Error ❌ | No results found.

### ISSUE THREAD

**Issue by taninsk137** [hmes98318/Music-Disc#18]
after I play any song
it will error
"❌ | No results found."

[edit]
if downgrade "discord-player" to "~6.0.0"
it will work normally

**Comment by hmes98318** [comment]
umm...I need some time to check the module's dependency issues.  
`v1.3.1`  has changed the stream extractor library.  
Have you installed the `play-dl` module and added the `DP_FORCE_YTDL_MOD = "play-dl"` environment variable?

**Comment by hmes98318** [comment]
These are the current dependency versions that I can run properly.  
```
music-disc@1.3.1 
├── console-stamp@3.1.1
├── discord-player@6.1.1
├── discord.js@14.7.1
├── dotenv@16.0.3
├── express@4.18.2
├── ffmpeg-static@5.1.0
├── ms@2.1.3
├── opusscript@0.0.8
└── play-dl@1.9.6
```

Could you provide the current operating system and npm modules version information?  
Because `discord-player` may encounter same errors and fail to run on some Linux distributions.

**Comment by taninsk137** [comment]
i run it on Glitch and this is "npm list" no error

music-disc@1.3.1 /app
├── console-stamp@3.1.1
├── discord-player@6.0.0
├── discord.js@14.9.0
├── dotenv@16.0.3
├── express@4.18.2
├── ffmpeg-static@5.1.0
├── ms@2.1.3
├── opusscript@0.0.8
└── play-dl@1.9.6

**Comment by taninsk137** [comment]
$ npm list
music-disc@1.3.1 /app
├── console-stamp@3.1.1
├── discord-player@6.1.1
├── discord.js@14.7.1
├── dotenv@16.0.3
├── express@4.18.2
├── ffmpeg-static@5.1.0
├── ms@2.1.3
├── opusscript@0.0.8
└── play-dl@1.9.6

I tried package like u mention above on Glitch
but I got error after playing song (command: .p song)
❌ | No results found.
If discord-player@6.0.0, its work

**Comment by hmes98318** [comment]
I can play music normally on Glitch using `v1.3.1` with discord-player `6.1.1` and `6.0.0` + play-dl.  

<img  width="800" src="https://user-images.githubusercontent.com/52697423/230407394-c6593d31-c7ba-4052-8ced-c6cbc5b18fb2.png">

If some specific sources (such as YouTube age restrictions) cannot be played and I haven't handled the exception.  
Do you get the same "No results found" problem when trying to play other songs?

**Comment by taninsk137** [comment]
I got "No results found" on all songs with discord-player 6.1.1 if seatch from text
ex. (.p babyshark) its not work with word
but works on link (.p https://www.youtube.com/watch?v=gqshCrI7sqc)
But no problem with discord-player 6.0.0

**Comment by hmes98318** [comment]
Oops, I didn't test the text search for the search command.  
I will fix this feature as soon as possible.

**Comment by hmes98318** [comment]
> I got "No results found" on all songs with discord-player 6.1.1 if search from text ex. (.p babyshark) its not work with word but works on link (.p https://www.youtube.com/watch?v=71KuVORecY8) But no problem with discord-player 6.0.0

Try update **discord.js** to `14.9.0`.

**Comment by taninsk137** [comment]
already tried discord.js@14.9.0
text search still not work but link works perfectly

**Comment by taninsk137** [comment]
i posted this error on discord-player's github

solution:
add this in the package
@discord-player/extractor

**Comment by hmes98318** [comment]
Got it! Thanks for the solution.

**Comment by taninsk137** [comment]
But when i queue it search in spotify not youtube... any fix?

**Comment by hmes98318** [comment]
Umm... the default query type is YouTube.  
I think can add an environment variable option to let you choose the query type by yourself.

**Comment by taninsk137** [comment]
I played the same song (.p ditto) and same code
"discord-player": "6.1.0"
results: youtube source
[*THREE DAYS ONLY* Easy 6 IV Ditto Raid Spotlight - Pokemon Scarlet and Violet](https://www.youtube.com/watch?v=IEZUhEGNe_E)
"discord-player": "6.1.1"
results: spotify source
[Ditto](https://open.spotify.com/track/3r8RuvgbX9s7ammBn07D3W)

**Comment by hmes98318** [comment]
<img src="https://user-images.githubusercontent.com/52697423/230630855-a166a803-6939-47b9-8615-1d20f68b6ded.png">

Sorry, I misspoke. The default query type for `discord-player` is AUTO, and most search results are primarily from YouTube.

**Comment by hmes98318** [comment]
The key should not be 'type'. Changing it to the following will make the response work:
https://github.com/hmes98318/Music-Disc/blob/62f76ad8ca3a1b2d4380a1813e7f73a8673f40d1/src/commands/play.js#L25

**Comment by taninsk137** [comment]
https://github.com/taninsk137/nonmaipor-2/blob/main/src/commands/play.js
I edited ur old code to the link above and it works.
I wait for ur update ^^

**Comment by hmes98318** [comment]
`v1.3.2` has been updated.
