### ISSUE TITLE
Skip and loop interfere with each other

### ISSUE THREAD

**Issue by Rainnfear** [hmes98318/Music-Disc#2]
Hello, my bot is working right but I can't skip music while the loop single is on, any way to skip this aside from stopping the loop or using command exit?

**Comment by hmes98318** [comment]
My original setting is that executing skip when `loop single` is on will play the same song repeatedly except `loop queue` or `loop off`.

**Comment by hmes98318** [comment]
I will modify this setting in the next version

**Comment by hmes98318** [comment]
@Rainnfear, new version updated.
