### ISSUE TITLE
Request for more stream extractor

### ISSUE THREAD

**Issue by neptalu0** [hmes98318/Music-Disc#22]
**Describe the Issue/Feature**
Allow support for Lavalink as stream extractor using libraries such as erela.js.

**Why this issue to happened / feature is needed(give scenarios or use cases):**
In terms of age-restricted playback, YTDL sources are a hassle since they require users to provide their own cookies, whereas Lavalink doesn't and only needs a host.

ps. I'm using freshly cloned git version and 2+ hours of testing

**Comment by hmes98318** [comment]
Sounds cool, I'll need some time to learn these tools.

**Comment by hmes98318** [comment]
New version coming soon [hmes98318/LavaShark](https://github.com/hmes98318/LavaShark)
