### ISSUE TITLE
There was a problem with the song queue => Cannot play a resource that has already ended.

### ISSUE THREAD

**Issue by taninsk137** [hmes98318/Music-Disc#26]
after the last patch

There was a problem with the song queue => Cannot play a resource that has already ended.

I think the problem is "discord-player": "6.3.0"

**Comment by hmes98318** [comment]
Please delete `node_modules/` and reinstall dependencies.

**Comment by taninsk137** [comment]
> Please delete `node_modules/` and reinstall dependencies.

i forked new project from ur github still get error

**Comment by hmes98318** [comment]
The current update is not yet complete.
Try installing the latest version `v1.4.1` instead of the latest commit.

```
git clone -b v1.4.1 https://github.com/hmes98318/Music-Disc.git
```
