### ISSUE TITLE
'maxvol' not working properly

### ISSUE THREAD

**Issue by HTF8** [hmes98318/Music-Disc#3]
The maxvol setting will not kick in until the volume level is manually changed, also causing it to reset when the bot rejoins the chat, whether leaving via autorejoin being set to false, DCing, or being booted.  If you set the volume, then maxvol will activate.  This makes the maxvol setting redundant, because if the bot doesn't leave the chat, his volume will stay the same anyway.  In the screenshot below my maxvol is set to 35, but the initial volume is at 100 when playing a song.  When I set it to 35, it correctly changes to 35/35.

![image](https://user-images.githubusercontent.com/33886223/200712348-336cc81e-90c8-486f-824e-8e9d89b0dfe0.png)

![image](https://user-images.githubusercontent.com/33886223/200712744-5e63f0e0-8573-48ff-b25c-6d9a5f7e47a4.png)

**Comment by hmes98318** [comment]
Show me your Music-Disc version and dependency modules

**Comment by HTF8** [comment]
@hmes98318 thanks.  let me know if these are the right ones.

```
  "name": "music-disc",
  "version": "1.2.1",
  "description": "Discord Music Bot",
  "main": "index.js",
```


```
  "dependencies": {
    "discord-player": "~5.3.1",
    "discord.js": "^14.5.0",
    "dotenv": "16.0.2",
    "express": "^4.18.1",
    "ffmpeg-static": "~5.1.0",
    "ms": "2.1.3",
    "opusscript": "~0.0.8"
  },
```

**Comment by hmes98318** [comment]
you need to use `npm list` command to get dependency modules.
If the `discord-player` version is 5.3.1 may get some volume problems
try `npm update discord-player` to update dependency module.

OR update `Music-Disc` to the [`latest`](https://github.com/hmes98318/Music-Disc/releases).

**Comment by HTF8** [comment]
@hmes98318 

```
├── discord-player@5.3.2
├── discord.js@14.5.0
├── dotenv@16.0.2
├── express@4.18.2
├── ffmpeg-static@5.1.0
├── ms@2.1.3
└── opusscript@0.0.8
```

**Comment by HTF8** [comment]
I updated Music-Disc to latest and reconfigured my `config.json`, seems to be working as expected now.  Thanks!
