### ISSUE TITLE
Got this error

### ISSUE THREAD

**Issue by taninsk137** [hmes98318/Music-Disc#30]
Error in the log:
There was a problem with the song queue => Cannot play a resource that has already ended.

in Discord its queue the song normally but there is no music playing in the channel.

**Comment by hmes98318** [comment]
Try kicking the bot out of the voice channel and then rejoining or restarting the bot.  
I need more time to investigate this error.

**Comment by taninsk137** [comment]
try kick the bot and rejoin the server, not working.
give admin role, not working
restart the bot, not working
i deployed it on glitch.com

**Comment by hmes98318** [comment]
Will the same error occur when using the Docker image as well?

**Comment by taninsk137** [comment]
sry, i didnt try that.

**Comment by hmes98318** [comment]
In version `v1.4.2`, I encountered the same error on **glitch.com**, but it worked fine on **replit.com**.  
I suspect that some npm modules are not compatible with the virtual machine's system.  
**glitch.com** uses Ubuntu 16.04.7 LTS, while **replit.com** uses Ubuntu 20.04.2 LTS.  
(Obtained detailed information using the status command.)

**Comment by taninsk137** [comment]
thanks ^^
