### ISSUE TITLE
Tanu

### ISSUE THREAD

**Issue by Priya7518** [hmes98318/Music-Disc#34]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Information:**
 - Node.js: x.x.x
 - Discord.js: x.x.x
 - Music-Disc: x.x.x
 - Dependency modules
     * discord-player: x.x.x
     * ffmpeg-static: x.x.x
     * opusscript: x.x.x
     * play-dl: x.x.x (or ytdl-core)

**Additional context**

**Comment by hmes98318** [comment]
Please write a valid context
