### ISSUE TITLE
The bot supports multiple nodes?

### ISSUE THREAD

**Issue by PM-KIRILL** [hmes98318/Music-Disc#42]
Is it possible to use the bot in a multi-node configuration? I would like to add multiple lavalink servers at once to share the load

**Comment by hmes98318** [comment]
Just modify [`nodelist.json`](https://github.com/hmes98318/Music-Disc/blob/2a9e7a3f1267d48a520a56806ae73d3ede618808/nodelist.json) to connect multiple lavalink nodes.  

```json
[
    {
        "id": "Node 1",
        "hostname": "x.x.x.x",
        "port": 2333,
        "password": "youshallnotpass"
    },
    {
        "id": "Node 2",
        "hostname": "x.x.x.x",
        "port": 2333,
        "password": "youshallnotpass"
    },
    { ... }
]
```

**Comment by PM-KIRILL** [comment]
Thanks
