### ISSUE TITLE
Cant play the music, it just finished after found the music

### ISSUE THREAD

**Issue by rivai45** [hmes98318/Music-Disc#49]
ENABLE_LOCAL_NODE = true
LOCAL_NODE_AUTO_RESTART = false

`ERROR 7460 --- [back-1-thread-1] d.l.y.cipher.SignatureCipherManager      : Problematic YouTube player script /s/player/e627e516/player_ias.vflset/id_ID/base.js detected (issue detected with script: no n function match)`

**Comment by hmes98318** [comment]
Please describe in detail which commit version the error occurred and attach a detailed execution log.

**Comment by rivai45** [comment]
Sorry, I dont know what is commit, but this is the logs from local node
[Local Node Logs.txt](https://github.com/user-attachments/files/17442185/Local.Node.Logs.txt)

I just play a song, then this
![image](https://github.com/user-attachments/assets/1f66bf2a-f634-41f4-9a96-084cc93d9cfb)

**Comment by hmes98318** [comment]
What is your bot version? (check package.json file)

**Comment by rivai45** [comment]
2.2.0

I follow your instruction `git clone -b v2.2.0 https://github.com/hmes98318/Music-Disc.git`

**Comment by hmes98318** [comment]
v3.0.0 is now available (Lavalink v4), please try using it to see if the same error occurs again.

**Comment by rivai45** [comment]
Now I get this error

![image](https://github.com/user-attachments/assets/370bceca-0d9d-4e72-b7ce-b26ff5cd55e8)

I use 3.0.0

**Comment by hmes98318** [comment]
Do other songs have the same error?
Is there a complete log output?

**Comment by rivai45** [comment]
Idk how, but now its work normally..
Strange :/

I will try to test several times

**Comment by rivai45** [comment]
I've test it.. Sometimes it can, sometimes it can't.
Just restart if it error
