### ISSUE TITLE
Bot volume

### ISSUE THREAD

**Issue by Oleniko1** [hmes98318/Music-Disc#52]
In the config example you can set a default volume of 50%
seems like it's not working as intendes since volume is 100% allways.
It seams like the /volume only applies to eatch song not the bot.

**Expected behavior**
configured in .env
DEFAULT_VOLUME = 50
expected the bot to have default volume to 50 not 100
**Screenshots**

**Version Information:**
![image](https://github.com/user-attachments/assets/0c675aa5-4b9a-4ae6-9078-f62d26c88800)

**Comment by hmes98318** [comment]
I have found the error and will fix it in the next version, thank you.

**Comment by hmes98318** [comment]
v3.1.0 fixed.

**Comment by hmes98318** [comment]
> I seem to have the same issue when I try after the update.

This problem did not occur after the example Bot was deployed.  
Please provide detailed execution records.

**Comment by hoehoetvhss** [comment]
I've tested with the original source and it seems that trying to play with the YouTube link outputs at the correct volume, but trying to play with the Spotify link doesn't play at the set volume.

**Comment by hmes98318** [comment]
> I've tested with the original source and it seems that trying to play with the YouTube link outputs at the correct volume, but trying to play with the Spotify link doesn't play at the set volume.

I can't reproduce your error, the default set volume all work fine.  
Please provide detailed execution records.  

![bot-volumn](https://github.com/user-attachments/assets/d99512b8-a74f-4634-9666-21720e206ad0)

**Comment by hoehoetvhss** [comment]
> > I've tested with the original source and it seems that trying to play with the YouTube link outputs at the correct volume, but trying to play with the Spotify link doesn't play at the set volume.
> 
> I can't reproduce your error, the default set volume all work fine. Please provide detailed execution records.
> 
> ![bot-volumn](https://private-user-images.githubusercontent.com/52697423/391383899-d99512b8-a74f-4634-9666-21720e206ad0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMTc0NjAsIm5iZiI6MTczMzExNzE2MCwicGF0aCI6Ii81MjY5NzQyMy8zOTEzODM4OTktZDk5NTEyYjgtYTc0Zi00NjM0LTk2NjYtMjE3MjBlMjA2YWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA1MjYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4OWU4MDRhNjIyZjU4NWQ2ZTYwODhhNjUwMTUzNjM4MjFkODYwNjg3MzdlMzAwZTlhMTgwZTJkNGU1MDkxN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.idjHBfBitwe4l3_4RUiNg9ilLwrcfSqstHnBs6wC3j4)

For comparison, I tested the original bot and my custom bot.

The default volume values are 50% for the original bot and 10% for my bot.

If you watch the [video](https://youtu.be/sZfczGMCMFw), you can see that the default volume is different, but when you play it with the Spotify link, it seems to play at the same volume.

**Comment by hmes98318** [comment]
@hoehoetvhss , I fixed this issue in commit c937c4a, you can test it.
